#!/bin/bash

for T in  janssen_pooled_real janssen_sa_real janssen_na_real janssen_la_real # janssen_pooled_realADCP janssen_sa_realADCP janssen_na_realADCP janssen_la_realADCP 
do
    export TRIAL=$T 
    echo $TRIAL
    make data_processed

done
