#!/bin/bash

# note that senior and nonsenior are split within the code and there are no separate labels in data processing for that

for T in  janssen_pooled_partA janssen_sa_partA janssen_na_partA janssen_la_partA 
do
    export TRIAL=$T 
    echo $TRIAL
    make data_processed

done



for T in  janssen_pooled_partA_VL janssen_sa_partA_VL janssen_na_partA_VL janssen_la_partA_VL 
do
    export TRIAL=$T 
    echo $TRIAL
    make data_processed

done
