#!/bin/bash

for T in  janssen_pooled_realbAb janssen_pooled_realADCP janssen_pooled_realPsV  janssen_na_realbAb janssen_na_realADCP janssen_na_realPsV janssen_la_realbAb janssen_la_realADCP janssen_la_realPsV janssen_sa_realbAb janssen_sa_realADCP janssen_sa_realPsV 
do
    export TRIAL=$T 
    echo $TRIAL
    make deploy_processed_dataset 

done
