# Check if only change in input dataset is marker data. 
# If so, simply pull the earlier risk scores and add to the new processed dataset!
generate_new_riskscores <- function(){
  source(here("code", "clean_output_dir.R"))
  source(here("code", "run_cvsl_riskscore.R"))
  source(here("code", "createRDAfiles_fromSLobjects.R"))
  source(here("code", "tables_figures.R"))
  source(here("code", "constructSL_getSLweights_Modelpredictors.R"))
  source(here("code", "predict_on_vaccine.R"))
  source(here("code", "append_risk_score_to_data.R"))
  source(here("code", "performance_on_vaccine.R"))
}

if(!study_name %in% c("COVE", "PROFISCOV")){
  if(file.exists(paste0("output/", Sys.getenv("TRIAL"), "/", "inputFile_with_riskscore.RData")) |
     (study_name == "ENSEMBLE" & file.exists(paste0("output/janssen_pooled_real/inputFile_with_riskscore.RData")))){
    
    if(study_name == "ENSEMBLE" & file.exists(paste0("output/janssen_pooled_real/inputFile_with_riskscore.RData"))){
      load("output/janssen_pooled_real/inputFile_with_riskscore.RData")
    }else{
      load(paste0("output/", Sys.getenv("TRIAL"), "/", "inputFile_with_riskscore.RData"))
    } 
    
    old_processed <- inputFile_with_riskscore %>%
      select(Ptid, Riskscorecohortflag, Trt, all_of(endpoint), all_of(original_risk_vars), risk_score, standardized_risk_score)
    
    new_processed <- inputFile %>%
      select(Ptid, Riskscorecohortflag, Trt, all_of(endpoint), all_of(original_risk_vars))
    
    if(all.equal(old_processed %>% select(-c(risk_score, standardized_risk_score)), new_processed) == TRUE){
      message("Variables related to risk score generation in input data have not changed. Superlearner will not be run. Risk scores from earlier run will be appended to raw data!")
      inputFile_with_riskscore <- left_join(inputFile,
                                            old_processed %>%
                                              select(Ptid, risk_score, standardized_risk_score), by = "Ptid")
      
      save(inputFile_with_riskscore, file = paste0("output/", Sys.getenv("TRIAL"), "/", "inputFile_with_riskscore.RData"))
    }else{
      message("Variables related to risk score generation in input data have changed! Superlearner needs to be run and new risk scores generated!")
      generate_new_riskscores()
    }
  }else{
    message(paste0("riskscore_baseline/", paste0("output/", Sys.getenv("TRIAL"), "/", "inputFile_with_riskscore.RData"), " does not exist. Superlearner needs to be run and new risk scores generated!"))
    generate_new_riskscores()
  }
}else if(study_name == "COVE"){
  inputFile_with_riskscore <- inputFile
  # Check 
  all.equal(names(inputFile_with_riskscore %>% select(Ptid, risk_score, standardized_risk_score)), c("Ptid", "risk_score", "standardized_risk_score"))
  print("Risk scores for Moderna real dataset were generated at Moderna's end using CoVPN Stats/SCHARP code and are already present in input file. Superlearner will not be run!")
  if(!file.exists(paste0("output/", Sys.getenv("TRIAL")))){
    dir.create(paste0("output/", Sys.getenv("TRIAL")))
  }
  save(inputFile_with_riskscore, file = paste0("output/", Sys.getenv("TRIAL"), "/", "inputFile_with_riskscore.RData"))
}else if(study_name == "PROFISCOV"){
  inputFile_with_riskscore <- inputFile %>% mutate(risk_score = 1,
                                                   standardized_risk_score = NA)
  # Check 
  all.equal(names(inputFile_with_riskscore %>% select(Ptid, risk_score)), c("Ptid", "risk_score"))
  print("All subjects for Butantan dataset are assigned risk score of 1. Risk scores are not generated by design. Superlearner will not be run!")
  if(!file.exists(paste0("output/", Sys.getenv("TRIAL")))){
    dir.create(paste0("output/", Sys.getenv("TRIAL")))
  }
  save(inputFile_with_riskscore, file = paste0("output/", Sys.getenv("TRIAL"), "/", "inputFile_with_riskscore.RData"))
}

# Perform sanity check if mock data!
source(here("code", "unit_test.R"))
